name: Notificare
port: 4444
url: http://notifica.re
permalink: pretty
exclude: [sass, config.rb, node_modules, Gemfile, Gemfile.lock, Gruntfile.js, package.json, README.md]
site_version: 1.0.3
facebook:
  app_id: 310676189002589
api:
  google:
    webmaster: YGzYOK4E7esrLNKKnMyHdwQjFP7GHOTz-tZezsXt4Eo
analytics:
  account: UA-32545615-1
data:
  plans:
    - name: Start Push
      url: startpush
      description: Get started with the power of smart push notifications. 
      price: 199
      users: 10000
      notifications: unlimited
      smartness: 
        - name: HTML Push
          icon: compass
        - name: Image Push
          icon: images
        - name: Map Push
          icon: map
        - name: Rating Push
          icon: star
        - name: Text Push
          icon: alert
      platforms: [Android, iOS, Websockets]
      api_access: yes
      storage: 5
      websockets: 20
    - name: More Push
      url: morepush
      description: Suitable for small/medium applications. More push, more functionality. 
      price: 399
      users: 50000
      notifications: unlimited
      smartness: 
        - name: HTML Push
          icon: compass
        - name: Image Push
          icon: images
        - name: Map Push
          icon: map
        - name: Rating Push
          icon: star
        - name: Text Push
          icon: alert
      platforms: [Android, iOS, Websockets]
      api_access: yes
      storage: 20
      websockets: 50
    - name: Force Push
      url: forcepush
      description: Our full featured plan. May the force of push be with you! 
      price: 599
      users: 100000
      notifications: unlimited
      smartness: 
        - name: HTML Push
          icon: compass
        - name: Image Push
          icon: images
        - name: Map Push
          icon: map
        - name: Rating Push
          icon: star
        - name: Text Push
          icon: alert
      platforms: [Android, iOS, Websockets]
      api_access: yes
      storage: 50
      websockets: 100
  testimonials:
    - name: Mangrove
      text: We have been using Notificare in all our apps and the result is just amazing. We almost forgot what is needed to integrate thanks to the incredibly easy drag and drop libraries.
      signature: Ruben Bos - Creative Director at Mangrove
      image: mangrove.png